// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {object} from '../models';
import {mazecontroller} from '../models';

export function CreateNewMaze(arg1:number):Promise<Array<any>>;

export function CreateQuestionBlock(arg1:Array<object.Card>):Promise<Array<mazecontroller.QuestBlock>>;
