// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewMaze(arg1) {
  return window['go']['mazecontroller']['Maze']['CreateNewMaze'](arg1);
}

export function CreateQuestionBlock(arg1) {
  return window['go']['mazecontroller']['Maze']['CreateQuestionBlock'](arg1);
}
