// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {object} from '../models';

export function AddNewDeck(arg1:object.DeckCreator):Promise<void>;

export function AddNewFolder(arg1:object.FolderCreator):Promise<void>;

export function DeleteItem(arg1:Array<string>):Promise<void>;

export function ExportDeck(arg1:object.DeckExpoter):Promise<string>;
