// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewDeck(arg1) {
  return window['go']['service']['Service']['AddNewDeck'](arg1);
}

export function AddNewFolder(arg1) {
  return window['go']['service']['Service']['AddNewFolder'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['service']['Service']['DeleteItem'](arg1);
}

export function ExportDeck(arg1) {
  return window['go']['service']['Service']['ExportDeck'](arg1);
}
