// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {object} from '../models';

export function CreateTest(arg1:object.TestCreator):Promise<object.TestCreateResult>;

export function GetDefaultTestResult():Promise<object.TestResult>;

export function TestCheck(arg1:Array<object.Answer>,arg2:string):Promise<object.TestResult>;
