// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTest(arg1) {
  return window['go']['pecontroller']['TestHandler']['CreateTest'](arg1);
}

export function GetDefaultTestResult() {
  return window['go']['pecontroller']['TestHandler']['GetDefaultTestResult']();
}

export function TestCheck(arg1, arg2) {
  return window['go']['pecontroller']['TestHandler']['TestCheck'](arg1, arg2);
}
