// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {object} from '../models';

export function LoadDeck(arg1:object.FLoader):Promise<Array<object.Card>>;

export function SaveDeck(arg1:object.DeckCreator):Promise<number>;

export function UpdateDeck(arg1:object.FileCreator):Promise<void>;
