// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDeck(arg1) {
  return window['go']['controller']['DeckHandler']['LoadDeck'](arg1);
}

export function SaveDeck(arg1) {
  return window['go']['controller']['DeckHandler']['SaveDeck'](arg1);
}

export function UpdateDeck(arg1) {
  return window['go']['controller']['DeckHandler']['UpdateDeck'](arg1);
}
