// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadFolder(arg1) {
  return window['go']['controller']['FolderHandler']['LoadFolder'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['controller']['FolderHandler']['SaveFolder'](arg1);
}

export function UpdateFolder(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['FolderHandler']['UpdateFolder'](arg1, arg2, arg3, arg4);
}
