// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {object} from '../models';

export function LoadFolder(arg1:object.FLoader):Promise<object.Metadata>;

export function SaveFolder(arg1:object.FolderCreator):Promise<number>;

export function UpdateFolder(arg1:object.FLoader,arg2:object.Data,arg3:string,arg4:boolean):Promise<void>;
