// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsFile(arg1, arg2) {
  return window['go']['controller']['Util']['IsFile'](arg1, arg2);
}
